Fig=figure('Name','Laborator Grafica',...
           'Units','normalized',...
           'Color', 'black',...
           'Position',[0.10 0.12 0.83 0.80]);

x=imread("background.png");
image(x);
set(gca,'Position',[0 0 1 1], 'Visible', 'off');

f=uimenu('Label','Proiect');
uimenu(f,'Label','Conexiunea EC','Callback','inceput_proiect');
uimenu(f,'Label','Autor proiect','Callback','open(''Autor.docx'')');
uimenu(f,'Label','Teorie','Callback','open(''teorie.docx'')'); 
uimenu(f,'Label','Bibliografie','Callback','open(''Biblografie.docx'')');
uimenu(f,'Label','Iesire','Callback','close');

B1=uicontrol('Style','text',...
           'Units','normalized',...
           'String','Tranzistor bipolar in conexiune emitor comun','FontSize',25,...
           'ForegroundColor','white',...
           'Background',[0.000 0.500 0.000],...               
           'Position',[0.3 0.7 0.4 0.12]);

B2=uicontrol('Style','Pushbutton',...
           'Units','normalized',...
           'String','Conexiunea EC','FontSize',16,...
           'ForegroundColor','white',...
           'Background',[0.000 0.500 0.000],...  
           'Position',[0.4 0.55 0.2 0.1],...
           'Callback', 'inceput_proiect');

Bpautor=uicontrol('Style','pushbutton',...         
           'Units','normalized',...       
           'Position',[0.12 0.5 0.15 0.08],...      
           'String','Autor','FontSize',16,...   
           'ForegroundColor','white',...
           'Background',[0.000 0.500 0.000],...
           'Callback','autor'); 

Bdocumentatie=uicontrol('Style','pushbutton',...         
           'Units','normalized',...       
           'Position',[0.12 0.4 0.15 0.08],...      
           'String','Teorie','FontSize',16,... 
           'ForegroundColor','white',...
           'Background',[0.000 0.500 0.000],...
           'Callback','teorie'); 

Bbiblografie=uicontrol('Style','pushbutton',...         
           'Units','normalized',...       
           'Position',[0.12 0.3 0.15 0.08],...      
           'String','Bibliografie','FontSize',16,...
           'ForegroundColor','white',...
           'Background',[0.000 0.500 0.000],...
           'Callback','biblografie'); 

BpECUATII=uicontrol('Style','pushbutton',...         
           'Units','normalized',...       
           'Position',[0.12 0.2 0.15 0.08],...      
           'String','Formule folosite','FontSize',16,... 
           'ForegroundColor','white',...
           'Background',[0.000 0.500 0.000],...
           'Callback','formule'); 

Bc=uicontrol('Style','pushbutton',...              
           'Units','normalized',...       
           'Position',[0.90 0.02 0.08 0.05],...  
           'String','IESIRE','FontSize',16,...  
           'ForegroundColor','white',...
           'Background',[0.000 0.500 0.000],...
           'Callback','close');